'use client';

import * as React from 'react';
import { Button } from '@/components/ui/Button';
import { ArrowLeft, RefreshCw, Copy, Download, Check } from 'lucide-react';
import RatingStars from '@/components/RatingStars';

interface ProjectProtocolResponse {
    success: boolean;
    request_id: string;
    project_name: string;
    project_summary: string;
    documents: {
        prd: string;
        architecture: string;
        stories: string;
    };
    analysis?: {
        project_name: string;
        core_features: string[];
        suggested_stack: {
            frontend: string;
            backend: string;
            database: string;
            hosting: string;
        };
        technical_complexity: string;
    };
    metrics: {
        total_tokens: number;
        processing_time_sec: number;
        api_cost_usd: number;
    };
    credits_used: number;
}

interface Props {
    result: ProjectProtocolResponse;
    onNewProject: () => void;
    onBack: () => void;
}

type TabType = 'prd' | 'architecture' | 'stories' | 'full';

export default function ProjectProtocolResults({ result, onNewProject, onBack }: Props) {
    const [activeTab, setActiveTab] = React.useState<TabType>('prd');
    const [copied, setCopied] = React.useState(false);

    // Get current document content based on active tab
    const getCurrentContent = () => {
        if (activeTab === 'full') {
            return getFullDocument();
        }
        return result.documents[activeTab];
    };

    // Combine all documents into one
    const getFullDocument = () => {
        return `# ${result.project_name} - Complete Project Documentation

Generated by Eloquo on ${new Date().toLocaleDateString()}

---

# Part 1: Product Requirements Document

${result.documents.prd}

---

# Part 2: Architecture Document

${result.documents.architecture}

---

# Part 3: Implementation Stories

${result.documents.stories}
`;
    };

    // Copy current section to clipboard
    const handleCopy = async () => {
        const content = getCurrentContent();
        await navigator.clipboard.writeText(content);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    // Download current section as .md file
    const handleDownloadSection = () => {
        const content = getCurrentContent();
        const safeName = result.project_name.replace(/\s+/g, '-').toLowerCase();
        const filename = activeTab === 'full'
            ? `${safeName}-complete.md`
            : `${safeName}-${activeTab}.md`;

        downloadFile(content, filename);
    };

    // Download all documents as single file
    const handleDownloadAll = () => {
        const content = getFullDocument();
        const safeName = result.project_name.replace(/\s+/g, '-').toLowerCase();
        downloadFile(content, `${safeName}-complete.md`);
    };

    // Helper to trigger file download
    const downloadFile = (content: string, filename: string) => {
        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    };

    const tabs = [
        { id: 'prd' as TabType, label: 'PRD' },
        { id: 'architecture' as TabType, label: 'Architecture' },
        { id: 'stories' as TabType, label: 'Stories' },
        { id: 'full' as TabType, label: '📄 Full Document' },
    ];

    return (
        <div className="min-h-screen bg-midnight p-4 md:p-6">
            <div className="max-w-5xl mx-auto">
                {/* Header */}
                <div className="flex items-center justify-between mb-6">
                    <button
                        onClick={onBack}
                        className="flex items-center gap-2 text-white/50 hover:text-electric-cyan transition-colors"
                    >
                        <ArrowLeft className="h-4 w-4" />
                        <span>Back to Optimize</span>
                    </button>
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={onNewProject}
                        className="border-electric-cyan/50 text-electric-cyan hover:bg-electric-cyan/10"
                    >
                        <RefreshCw className="h-4 w-4 mr-2" />
                        New Project
                    </Button>
                </div>

                {/* Success Banner */}
                <div className="flex items-center gap-2 text-electric-cyan mb-4">
                    <span className="text-xl">✅</span>
                    <span className="text-lg font-medium uppercase tracking-wider">PROJECT GENERATED</span>
                </div>

                {/* Project Summary Card */}
                <div className="bg-midnight/80 border border-electric-cyan/30 rounded-xl p-6 mb-6">
                    <h1 className="text-2xl md:text-3xl font-bold text-white mb-2">
                        {result.project_name}
                    </h1>
                    <p className="text-white/60 leading-relaxed">
                        {result.project_summary}
                    </p>
                </div>

                {/* Tabs */}
                <div className="flex flex-wrap border-b border-electric-cyan/30 mb-4">
                    {tabs.map((tab) => (
                        <button
                            key={tab.id}
                            onClick={() => setActiveTab(tab.id)}
                            className={`px-4 md:px-6 py-3 font-medium transition-colors ${activeTab === tab.id
                                ? 'text-electric-cyan border-b-2 border-electric-cyan bg-electric-cyan/10'
                                : 'text-white/50 hover:text-white hover:bg-white/5'
                                }`}
                        >
                            {tab.label}
                        </button>
                    ))}
                </div>

                {/* Document Content */}
                <div className="bg-midnight/80 border border-electric-cyan/30 rounded-xl p-4 md:p-6 mb-6 max-h-[60vh] overflow-y-auto">
                    <pre className="whitespace-pre-wrap font-mono text-sm text-white/80 leading-relaxed">
                        {getCurrentContent()}
                    </pre>
                </div>

                {/* Action Bar */}
                <div className="bg-midnight/80 border border-electric-cyan/30 rounded-xl p-4">
                    <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
                        {/* Action Buttons */}
                        <div className="flex flex-wrap gap-3">
                            <Button
                                variant="outline"
                                size="sm"
                                onClick={handleCopy}
                                className="border-electric-cyan/50 text-electric-cyan hover:bg-electric-cyan/10"
                            >
                                {copied ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                                {copied ? 'Copied!' : 'Copy Section'}
                            </Button>
                            <Button
                                variant="outline"
                                size="sm"
                                onClick={handleDownloadSection}
                                className="border-electric-cyan/50 text-electric-cyan hover:bg-electric-cyan/10"
                            >
                                <Download className="h-4 w-4 mr-2" />
                                Download Section
                            </Button>
                            <Button
                                variant="default"
                                size="sm"
                                onClick={handleDownloadAll}
                                className="bg-electric-cyan text-midnight hover:bg-electric-cyan/90"
                            >
                                <Download className="h-4 w-4 mr-2" />
                                Download All
                            </Button>
                        </div>

                        {/* Metrics */}
                        <div className="flex items-center gap-4 md:gap-6 text-xs md:text-sm text-white/50">
                            <span className="flex items-center gap-1">
                                <span>⏱</span>
                                <span>{(result.metrics?.processing_time_sec ?? 0).toFixed(1)}s</span>
                            </span>
                            <span className="flex items-center gap-1">
                                <span>📊</span>
                                <span>{(result.metrics?.total_tokens ?? 0).toLocaleString()} tokens</span>
                            </span>
                            <span className="flex items-center gap-1">
                                <span>🎫</span>
                                <span>{result.credits_used ?? 5} credits</span>
                            </span>
                        </div>
                    </div>

                    {/* Rating Stars */}
                    <div className="border-t border-electric-cyan/20 mt-4 pt-2">
                        <RatingStars requestId={result.request_id} />
                    </div>
                </div>
            </div>
        </div>
    );
}
